spring:
  application:
    name: api-gateway

#api gateway config
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
          - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2

#eureka client config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#  instance:
#    instance-id: ${spring.application.name}:${server.port}
#    prefer-ip-address: true
#    hostname: localhost




